Repository CodeChain-io/codechain-indexer, pull requests merged in 2019-02, with the labels that each got.

#52 Fix the bug that occurred when the payment quantity is large
  src/models/logic/pay.ts
  src/models/logic/transaction.ts
  test/payment.spec.ts
Labels: bug

#60 The approver of ComposeAsset can be null
  src/models/composeAsset.ts
Labels: bug

#67 Add a transactionTracker field to the UTXO model
  src/migrations/20181221095118-create-utxo.js
  src/models/logic/transaction.ts
  src/models/logic/utxo.ts
  src/models/utxo.ts
Labels: enhancement

#75 Add a workaround for a runtime error in handleUTXO()
  src/models/logic/transaction.ts
Labels: bug

#78 Parameters of the input can be undefined
  src/models/logic/assettransferburn.ts
  src/models/logic/assettransferinput.ts
Labels: bug

#99 Change the type option query to be comma separated
  src/models/logic/transaction.ts
  src/routers/transaction.ts
Labels: enhancement

#116 Remove e2e-test
  .travis.yml
  e2e-test/README.md
  e2e-test/package.json
  e2e-test/scripts/createFixture.ts
  e2e-test/scripts/pullCodeChainDocker.ts
  e2e-test/sqls/README.md
  e2e-test/sqls/payment.sql
  e2e-test/src/cleanUp.ts
  e2e-test/src/codeChain.ts
  e2e-test/src/db.ts
  e2e-test/src/indexer/index.ts
  e2e-test/src/indexer/rpc.ts
  e2e-test/src/logger.ts
  e2e-test/src/sdkExample.ts
  e2e-test/src/test/payment.test.ts
  e2e-test/src/test/sample.test.ts
  e2e-test/tsconfig.json
  e2e-test/tslint.json
  e2e-test/yarn.lock
  package.json
Labels: test

#132 Fix "TypeError: Cannot read property 'startsWith' of undefined"
  src/models/logic/assettransferburn.ts
  src/models/logic/assettransferinput.ts
Labels: bug

#133 Fix "Error: InvalidUTXO"
  src/models/logic/transaction.ts
Labels: bug
