Repository CodeChain-io/codechain-indexer, pull requests merged in 2019-03, with the labels that each got.

#135 Change the worker to use AsyncLock
  package.json
  src/worker/index.ts
  yarn.lock
Labels: bug

#136 Change the pending transactions API to support the pagination query
  src/models/logic/transaction.ts
  src/routers/transaction.ts
Labels: enhancement

#139 Fix bugs of getPendingTransactions() and getTransactions()
  src/models/logic/transaction.ts
  src/models/logic/utils/includeArray.ts
Labels: bug

#142 Fix the runtime error of updateAssetScheme()
  src/models/logic/assetscheme.ts
  src/models/logic/transaction.ts
Labels: bug

#144 Optimize indexPendingTransaction() by implementing getAllPendingTrans…
  src/models/logic/transaction.ts
  src/worker/index.ts
Labels: optimization

#145 Add a publicAddress field to the config
  config/default.json
  src/config.ts
  src/server.ts
Labels: maintenance

#150 Cleanup
  src/models/logic/changeAssetScheme.ts
  src/models/logic/composeAsset.ts
  src/models/logic/createShard.ts
  src/models/logic/custom.ts
  src/models/logic/decomposeAsset.ts
  src/models/logic/increaseassetsupply.ts
  src/models/logic/mintAsset.ts
  src/models/logic/pay.ts
  src/models/logic/remove.ts
  src/models/logic/setRegularKey.ts
  src/models/logic/setShardOwners.ts
  src/models/logic/setShardUsers.ts
  src/models/logic/store.ts
  src/models/logic/transaction.ts
  src/models/logic/transferAsset.ts
  src/models/logic/unwrapCCC.ts
  src/models/logic/wrapCCC.ts
Labels: maintenance

#151 Utilize workerpool to get the signers of transactions
  package.json
  src/models/logic/transaction.ts
  src/models/logic/utils/workerpool.ts
  yarn.lock
Labels: optimization

#156 Add an index field to the AssetTransferOutput table
  src/migrations/20181223012324-create-asset-transfer-output.js
  src/models/assettransferoutput.ts
  src/models/logic/assettransferoutput.ts
  src/models/logic/decomposeAsset.ts
  src/models/logic/transferAsset.ts
  src/models/logic/utxo.ts
Labels: bug

#161 Add an index field to the AssetTransferInput, AssetTransferBurn, and …
  src/migrations/20181223012209-create-asset-transfer-input.js
  src/migrations/20181223015222-create-asset-transfer-burn.js
  src/migrations/20190131074418-create-order-on-transfer.js
  src/models/assettransferburn.ts
  src/models/assettransferinput.ts
  src/models/logic/assettransferburn.ts
  src/models/logic/assettransferinput.ts
  src/models/logic/composeAsset.ts
  src/models/logic/decomposeAsset.ts
  src/models/logic/orderontransfer.ts
  src/models/logic/transferAsset.ts
  src/models/logic/unwrapCCC.ts
  src/models/orderontransfer.ts
Labels: bug

#160 Use DISTINCT for a transaction hash when counting transactions
  src/models/logic/transaction.ts
Labels: bug

#155 Add tests for the router APIs
  src/routers/status.ts
  test/api.spec.ts
  test/api/account.spec.ts
  test/api/asset.spec.ts
  test/api/block.spec.ts
  test/api/log.spec.ts
  test/api/status.spec.ts
  test/api/transaction.spec.ts
Labels: test

#162 Sort transactions in a block
  src/models/logic/block.ts
  src/models/logic/transaction.ts
Labels: bug

#165 Update the SDK version
  .travis.yml
  package.json
  src/worker/index.ts
  test/pending-tx.spec.ts
  yarn.lock
Labels: update

#164 Add an includePending query to the tx routes
  src/models/logic/transaction.ts
  src/routers/transaction.ts
  src/routers/validator.ts
Labels: enhancement

#167 Don't skip the /tx/count test
  test/api/transaction.spec.ts
Labels: test

#179 Store a decimal string for quantity in transactions
  src/models/logic/decomposeAsset.ts
  src/models/logic/transferAsset.ts
  src/models/logic/unwrapCCC.ts
Labels: bug

#181 Remove unused tables
  src/migrations/20181223012209-create-asset-transfer-input.js
  src/migrations/20181223015222-create-asset-transfer-burn.js
  src/migrations/20190131074418-create-order-on-transfer.js
  src/migrations/20190131075705-create-order.js
  src/models/assettransferburn.ts
  src/models/assettransferinput.ts
  src/models/index.ts
  src/models/logic/assettransferburn.ts
  src/models/logic/assettransferinput.ts
  src/models/logic/order.ts
  src/models/logic/orderontransfer.ts
  src/models/order.ts
  src/models/orderontransfer.ts
Labels: maintenance

#185 Wait before closing the sequelize
  test/api/account.spec.ts
  test/api/asset.spec.ts
  test/api/block.spec.ts
  test/api/log.spec.ts
  test/api/status.spec.ts
  test/api/transaction.spec.ts
Labels: test

#187 Fix the 500 error of /block/:hashOrNumber/tx
  src/routers/block.ts
Labels: bug
